on: [push, pull_request]

name: "Code Hygiene Suite"

env:
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  hygiene:
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
        features: [default, mcp]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      # - name: Install dependencies (Ubuntu only)
      #   if: matrix.platform == 'ubuntu-latest'
      #   run: |
      #       sudo apt-get update
      #       sudo apt-get install -y libdbus-1-dev pkg-config

      - name: rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Initialize Rust Cache
        uses: actions/cache@v5
        with:
          path: |
            ~/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ matrix.features }}

      - name: cargo check
        run: cargo check --all-targets ${{ matrix.features == 'mcp' && '--features mcp' || '' }}

      - name: cargo fmt
        if: matrix.features == 'default'
        run: cargo fmt --all -- --check

      - name: cargo clippy
        run: cargo clippy --all-targets ${{ matrix.features == 'mcp' && '--features mcp' || '' }} -- -D warnings
