name: "Testing Suite"
on: [push, pull_request]

jobs:
  unit-test:
    permissions:
      contents: write
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true

      - name: Initialize Rust Cache
        uses: actions/cache@v6
        with:
          path: |
            ~/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Run test suite
        working-directory: ./
        run: cargo test

      - name: Do a simple build
        working-directory: ./
        run: cargo build
